# Generated by Django 6.0.7 on 2026-07-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('address', models.TextField(max_length=200)),
                ('blood_group', models.CharField(max_length=60)),
                ('doctor_name', models.CharField(max_length=60)),
                ('is_admitted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
