# Generated by Django 6.0.7 on 2026-07-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorname', models.CharField(max_length=100)),
                ('directorbio', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
                ('categorydescription', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movietitle', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('releasedate', models.DateTimeField()),
                ('language', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('directorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.director')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.moviecategory')),
            ],
        ),
    ]
