# Generated by Django 6.0.7 on 2026-07-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=60)),
                ('price', models.FloatField()),
                ('languages', models.CharField(max_length=100)),
                ('isbnNumber', models.BigIntegerField()),
                ('edition', models.CharField(max_length=10)),
                ('totalPages', models.IntegerField()),
                ('publisher', models.CharField(max_length=60)),
                ('publicationDate', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
