# Generated by Django 6.0.7 on 2026-07-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=200)),
                ('price', models.FloatField()),
                ('pages_count', models.IntegerField(max_length=60)),
                ('sold_count', models.IntegerField(max_length=60)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
