# Generated by Django 6.0.7 on 2026-07-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MEMBER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('MEMBERSHIP_TYPE', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half-yearly', 'Half-Yearly'), ('yearly', 'Yearly')], max_length=60)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('discount', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_availble', models.BooleanField(default=True, verbose_name='Available Status')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memeber_name', models.CharField(max_length=100)),
                ('package_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'Upi'), ('card', 'Card'), ('net banking', 'Net Banking')], max_length=100)),
                ('payment_date', models.DateField()),
                ('receipt_no', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], max_length=100)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Status')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TRAINER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('SPECIALIZATION', models.CharField(choices=[('cardio', 'Cardio'), ('yoga', 'Yoga'), ('weight training', 'Weight Training'), ('crossfit', 'CrossFit')], max_length=60)),
                ('experience', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
                ('is_available', models.BooleanField(default=True, verbose_name='Available Status')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
