# Generated by Django 6.0.7 on 2026-07-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailynews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='titel',
            new_name='title',
        ),
    ]
