# Generated by Django 6.0.7 on 2026-07-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_address', models.CharField(max_length=100)),
                ('pickup_place', models.CharField(max_length=100)),
                ('dropoff_place', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('desial', 'Desial'), ('petrol', 'Petrol'), ('cng', 'CNG')], max_length=100)),
                ('rental_price', models.FloatField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
